### ISSUE TITLE
Items load

### ISSUE THREAD

**Issue by EugeneSel** [lajavaness/annotto-api#4]
**Describe the bug**
For all the new projects, the items (text or images) never load. Console indicates the "_Failed to load response data. No data found for resource with given identifier_" error.

**To Reproduce**
1. Start creating a new annotto project.
2. Add any items.
3. Fill other fields in.
4. Create the project.
5. Try to open any item.

**Expected behavior**
The selected item should appear.

**Screenshots**
<img width="1792" alt="Capture d’écran 2022-06-24 à 15 28 05" src="https://user-images.githubusercontent.com/23023418/175545937-03035d67-55fe-4f6e-9066-8c4dd0072c84.png">

**Desktop**
 - OS: iOS
 - Browser: chrome
 - Version: 102.0.5005.115

**Comment by manodupont** [comment]
@EugeneSel  Can you add more details on this please like the items jsonline files you were using.
I was able to create a project of type "text" and adding items.jsonlines that contains `datatype: 'text'` by doing
1. Create new project
2. Filling the fields under the "Project Details" first step
3. I imported a file that contains items in jsonline format such as this line ```{"uuid": "d6da2c5c-ac83-49ab-ba90-5ff73bc902f6", "datatype": "text", "data": {"text": "Poste de livraison client\nJustification de la stratégie retenue\n3.1- Présentation de la stratégie retenue \nLe point de livraison du client se trouve sur la parcelle contiguë au poste 90 kV de la Mothe Saint Heray dont le foncier appartient à l’ELD Geredis.\nLa solution consiste à raccorder le client en antenne souterraine (environ 100m) au poste 90 kV de la Mothe Saint Heray.\nUne solution de raccordement avec 2 disjoncteurs est proposée malgré la proximité du poste Producteur car : \n- La position précise du poste de livraison du client n’est pas connue à ce stade des études ;\n- Un raccordement à 1 disjoncteur nécessite la signature d’une convention entre Geredis et le Producteur pour les accès et interventions dans le poste.\nLa capacité réservée au poste"}}```
4. I clicked on "Publish"
5. I can see my item in the text field when I clicked on it. See picture below :
<img width="1536" alt="Screenshot 2022-06-24 at 16 28 17" src="https://user-images.githubusercontent.com/7568033/175556660-fce6f9ed-7f03-409d-851d-81ff09629e18.png">

Maybe you can give me the actual new project config you set, and also, try to create a jsonline file with only one item to narrow down the problem to a single item.

**Comment by EugeneSel** [comment]
@manodupont simplified version with only one item, I attached the config as well (without S3 credentials).
Still encountering the same problem
[project_segment_test.zip](https://github.com/lajavaness/annotto-api/files/8977038/project_segment_test.zip)
.

**Comment by manodupont** [comment]
You need to add your AWS configuration to your project `config.json` file if you import items with s3 url.
